name = "webterm"
pages_build_output_dir = "./target"

main = "./src/main.rs"
compatibility_date = "2024-11-19"

[build]
command = "cargo install dioxus-cli && dx serve --release"

[env.dev]
build = { command = "cargo install dioxus-cli && dx serve" }

[placement]
mode = "smart"